services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - eth

  scanner:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m scanner.async_scanner
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - eth

  executor:
    build:
      context: .
      dockerfile: Dockerfile
    command: python trade_executor.py
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - eth

networks:
  eth: {}







